package com.techown.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-08T19:17:43.336+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "SendSmsServiceService", 
                  wsdlLocation = "http://www.106dcx.com:16373/SMSService/webService/sms?wsdl",
                  targetNamespace = "http://service.techown.com/") 
public class SendSmsServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.techown.com/", "SendSmsServiceService");
    public final static QName SendSmsServicePort = new QName("http://service.techown.com/", "SendSmsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.106dcx.com:16373/SMSService/webService/sms?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SendSmsServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.106dcx.com:16373/SMSService/webService/sms?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SendSmsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendSmsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendSmsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SendSmsService
     */
    @WebEndpoint(name = "SendSmsServicePort")
    public SendSmsService getSendSmsServicePort() {
        return super.getPort(SendSmsServicePort, SendSmsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSmsService
     */
    @WebEndpoint(name = "SendSmsServicePort")
    public SendSmsService getSendSmsServicePort(WebServiceFeature... features) {
        return super.getPort(SendSmsServicePort, SendSmsService.class, features);
    }

}
