
package com.techown.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-08T19:17:43.242+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class SendSmsService_SendSmsServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.techown.com/", "SendSmsServiceService");

    private SendSmsService_SendSmsServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SendSmsServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SendSmsServiceService ss = new SendSmsServiceService(wsdlURL, SERVICE_NAME);
        SendSmsService port = ss.getSendSmsServicePort();  
        
        {
        System.out.println("Invoking batchSend...");
        java.lang.String _batchSend_userName = "";
        java.lang.String _batchSend_passWord = "";
        java.lang.String _batchSend_smsContent = "";
        java.lang.String _batchSend_fileName = "";
        java.lang.String _batchSend_sendTime = "";
        java.lang.String _batchSend_smsPriority = "";
        java.lang.String _batchSend_sendAppId = "";
        java.lang.String _batchSend__return = port.batchSend(_batchSend_userName, _batchSend_passWord, _batchSend_smsContent, _batchSend_fileName, _batchSend_sendTime, _batchSend_smsPriority, _batchSend_sendAppId);
        System.out.println("batchSend.result=" + _batchSend__return);


        }
        {
        System.out.println("Invoking variableSend...");
        java.lang.String _variableSend_userName = "";
        java.lang.String _variableSend_passWord = "";
        java.lang.String _variableSend_variableTemplateContent = "";
        java.lang.String _variableSend_fileName = "";
        java.lang.String _variableSend_sendTime = "";
        java.lang.String _variableSend_smsPriority = "";
        java.lang.String _variableSend_sendAppId = "";
        java.lang.String _variableSend__return = port.variableSend(_variableSend_userName, _variableSend_passWord, _variableSend_variableTemplateContent, _variableSend_fileName, _variableSend_sendTime, _variableSend_smsPriority, _variableSend_sendAppId);
        System.out.println("variableSend.result=" + _variableSend__return);


        }
        {
        System.out.println("Invoking querySendAppLog...");
        java.lang.String _querySendAppLog_userName = "";
        java.lang.String _querySendAppLog_passWord = "";
        java.lang.String _querySendAppLog_sendTime = "";
        java.lang.String _querySendAppLog__return = port.querySendAppLog(_querySendAppLog_userName, _querySendAppLog_passWord, _querySendAppLog_sendTime);
        System.out.println("querySendAppLog.result=" + _querySendAppLog__return);


        }
        {
        System.out.println("Invoking massSend...");
        java.lang.String _massSend_userName = "";
        java.lang.String _massSend_passWord = "";
        java.lang.String _massSend_smsContent = "";
        java.lang.String _massSend_cellPhone = "";
        java.lang.String _massSend_sendTime = "";
        java.lang.String _massSend_smsPriority = "";
        java.lang.String _massSend_sendAppId = "";
        java.lang.String _massSend__return = port.massSend(_massSend_userName, _massSend_passWord, _massSend_smsContent, _massSend_cellPhone, _massSend_sendTime, _massSend_smsPriority, _massSend_sendAppId);
        System.out.println("massSend.result=" + _massSend__return);


        }

        System.exit(0);
    }

}
